#' High-Precision Multi-Trait Cause-and-Effect Path Coefficient Analysis Engine
#'
#' @description
#' The `compute_path_analysis` function executes phenotypic and genotypic path coefficient 
#' analysis based on the classic standard methodology of Dewey and Lu (1959). It partitions 
#' correlation coefficients between causal developmental traits and a target response 
#' variable into direct influence coefficients and indirect pathways acting through interconnected traits.
#'
#' @details
#' Path coefficient analysis provides a matrix-based decomposition of direct and indirect 
#' components. For a target response variable, let \eqn{R} denote the correlation matrix 
#' among causal predictor traits, and \eqn{r} denote the vector of correlations between 
#' predictors and the response variable. Standardized direct path coefficients (\eqn{\beta}) 
#' are calculated via matrix inversion:
#' \deqn{\beta = R^{-1} r}
#' Indirect effects are cross-products between inter-trait correlations and direct path 
#' coefficients. The unexplained residual effect (\eqn{R_X}) is derived as:
#' \deqn{R_X = \sqrt{1 - \sum (\beta_i \times r_i)}}
#'
#' @param correlation_payload A structured \code{list} generated by \code{compute_correlation} 
#'    containing \code{genotypic_correlation} and/or \code{phenotypic_correlation} matrices, or a single matrix.
#' @param response_trait A single character string specifying the target dependent trait column name.
#' @param predictor_traits A character vector identifying the causal predictor traits. 
#'    If \code{NULL}, all remaining numeric traits except non-agronomic design factors and \code{response_trait} are automatically selected.
#' @param reporting_level An integer flag defining console output verbosity: \code{0} for silent execution, 
#'    \code{1} for path decomposition summary, and \code{2} for detailed separate component tables. Defaults to \code{2}.
#'
#' @return A structured named \code{list} containing path partition analyses for available correlation levels (\code{Genotypic} and/or \code{Phenotypic}):
#' \item{direct_effects}{Numeric vector storing standardized direct path coefficients (\eqn{\beta}).}
#' \item{indirect_effects_matrix}{Data frame capturing inter-trait indirect path components alongside total correlation.}
#' \item{total_correlation_vector}{Original correlation alignment vector with the target response trait.}
#' \item{residual_effect}{Unexplained model residual variation (\eqn{R_X}).}
#' \item{r_squared}{Total variance explained by causal predictors (\eqn{R^2}).}
#' \item{predictors}{Character vector of causal predictor traits included in the pathway model.}
#'
#' @seealso \code{\link{compute_correlation}}, \code{\link{compute_summary_stats}}
#'
#' @export
#'
#' @examples
#' \donttest{
#'    # Compute multi-level correlation matrices
#'    corr_payload <- compute_correlation(data = gv_data, reporting_level = 0)
#'    
#'    # Define all 6 causal predictor traits driving Grain Yield per Meter
#'    all_predictors <- c("PH", "SL", "PL", "NOT", "NOSS", "TGW")
#'    
#'    # Run path coefficient analysis across all causal traits with full report
#'    path_out <- compute_path_analysis(
#'      correlation_payload = corr_payload, 
#'      response_trait = "GYPM",
#'      predictor_traits = all_predictors,
#'      reporting_level = 2
#'    )
#' }
compute_path_analysis <- function(correlation_payload, response_trait, predictor_traits = NULL, reporting_level = 2) {
  
  if (missing(correlation_payload) || missing(response_trait)) {
    stop("CRITICAL MATRIX FAULT: Missing core arguments (correlation_payload or response_trait).", call. = FALSE)
  }
  
  # Helper function for single matrix path calculation dynamically
  calculate_path_matrix <- function(corr_matrix, response, predictors) {
    corr_mat <- data.matrix(corr_matrix)
    all_traits <- colnames(corr_mat)
    
    if (is.null(all_traits)) {
      all_traits <- rownames(corr_mat)
      colnames(corr_mat) <- all_traits
      rownames(corr_mat) <- all_traits
    }
    
    if (!response %in% all_traits) {
      stop(paste0("REGISTRATION FAULT: Response trait '", response, "' not found in correlation matrix columns."), call. = FALSE)
    }
    
    # Auto-filter design variables if predictors are not explicitly specified (Fully Dynamic)
    if (is.null(predictors)) {
      exclude_vars <- c(response, "Replication", "Rep", "Replications", "Block", "Env", "Environment", "Genotype", "Line", "Cultivar")
      predictors <- setdiff(all_traits, exclude_vars)
    }
    
    # Validate predictor presence
    valid_predictors <- intersect(predictors, all_traits)
    valid_predictors <- setdiff(valid_predictors, response)
    
    if (length(valid_predictors) == 0) {
      stop("VALIDATION FAULT: No valid predictor traits found in correlation matrix.", call. = FALSE)
    }
    
    num_pred <- length(valid_predictors)
    matrix_R <- corr_mat[valid_predictors, valid_predictors, drop = FALSE]
    vector_r <- as.numeric(corr_mat[valid_predictors, response])
    names(vector_r) <- valid_predictors
    
    # Direct Path Coefficients Vector with robust singular/collinear fallback
    matrix_R_inv <- tryCatch({
      solve(matrix_R)
    }, error = function(e) {
      # Fallback to pseudo-inverse solver (qr.solve) in case of near-singularity
      tryCatch({
        qr.solve(matrix_R)
      }, error = function(e2) {
        stop("MATHEMATICAL FAULT: Correlation matrix among predictors is severely singular. Matrix inversion failed.", call. = FALSE)
      })
    })
    
    direct_effects <- as.numeric(matrix_R_inv %*% vector_r)
    names(direct_effects) <- valid_predictors
    
    # Full Path Matrix Construction (Diagonal = Direct, Off-Diagonal = Indirect)
    path_matrix <- matrix(0, nrow = num_pred, ncol = num_pred,
                          dimnames = list(valid_predictors, valid_predictors))
    
    for (i in 1:num_pred) {
      for (j in 1:num_pred) {
        path_matrix[i, j] <- if (i == j) direct_effects[i] else matrix_R[i, j] * direct_effects[j]
      }
    }
    
    df_path <- as.data.frame(path_matrix)
    df_path$Total_Correlation <- vector_r
    
    # Residual and Explained Variance Calculation
    r_sq_exp <- sum(direct_effects * vector_r)
    residual_val <- if (r_sq_exp > 1 || r_sq_exp < 0) 0 else sqrt(max(0, 1 - r_sq_exp))
    
    return(list(
      direct_effects = direct_effects,
      indirect_effects_matrix = df_path,
      total_correlation_vector = vector_r,
      residual_effect = residual_val,
      r_squared = r_sq_exp,
      predictors = valid_predictors
    ))
  }
  
  results <- list()
  
  # Extract components dynamically from compute_correlation output list
  if (is.list(correlation_payload)) {
    g_mat <- if (!is.null(correlation_payload$genotypic_correlation)) {
      correlation_payload$genotypic_correlation
    } else if (!is.null(correlation_payload$Genotypic)) {
      correlation_payload$Genotypic
    } else {
      NULL
    }
    
    p_mat <- if (!is.null(correlation_payload$phenotypic_correlation)) {
      correlation_payload$phenotypic_correlation
    } else if (!is.null(correlation_payload$Phenotypic)) {
      correlation_payload$Phenotypic
    } else {
      NULL
    }
    
    if (!is.null(g_mat)) {
      results$Genotypic <- calculate_path_matrix(g_mat, response_trait, predictor_traits)
    }
    if (!is.null(p_mat)) {
      results$Phenotypic <- calculate_path_matrix(p_mat, response_trait, predictor_traits)
    }
    
    if (length(results) == 0 && "correlation_matrix" %in% names(correlation_payload)) {
      results$Phenotypic <- calculate_path_matrix(correlation_payload$correlation_matrix, response_trait, predictor_traits)
    }
  }
  
  if (length(results) == 0) {
    results$Phenotypic <- calculate_path_matrix(correlation_payload, response_trait, predictor_traits)
  }
  
  # Console Output Execution for both Genotypic and Phenotypic levels
  if (reporting_level >= 1) {
    cat("\n", rep("=", 90), "\n", sep = "")
    cat("           AGRIDATATOOLS: GENOTYPIC & PHENOTYPIC PATH ANALYSIS REPORT\n")
    cat("           Target Response Trait (Effect): ", response_trait, "\n", sep = "")
    cat(rep("=", 90), "\n", sep = "")
    
    for (type in names(results)) {
      res <- results[[type]]
      
      cat("\n", rep("-", 90), "\n", sep = "")
      cat(" TABLE: ", toupper(type), " PATH COEFFICIENTS MATRIX\n", sep = "")
      cat(rep("-", 90), "\n", sep = "")
      
      print(round(res$indirect_effects_matrix, 5))
      
      cat("\n [ DIRECT EFFECTS (Diagonal Values) ]:\n")
      print(round(res$direct_effects, 5))
      
      cat("\n Model Statistics:\n")
      cat("  * R-Squared Explained (R^2) : ", round(res$r_squared, 5), "\n", sep = "")
      cat("  * Residual Effect (Rx)       : ", round(res$residual_effect, 5), "\n", sep = "")
      cat(rep("-", 90), "\n", sep = "")
    }
  }
  
  return(invisible(results))
}